name: Lint

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: pip
        cache-dependency-path: '**/requirements*.txt'

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip wheel
        make native-install-all

    - name: Run lint
      run: |
        make native-lint
